name: forum_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.5 <3.0.0"

dependencies:
  cloud_firestore: ^4.8.1
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  flutter_form_builder: ^9.0.0
  flutter:
    sdk: flutter
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.24.1
  mockito: ^5.4.2
  build_runner: ^2.4.5

flutter:
  uses-material-design: true
