// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVQCor0ZkUjtholqADTrxqNPK4rycOw0M',
    appId: '1:823475181285:web:6e8f68ab2fddf436e7260c',
    messagingSenderId: '823475181285',
    projectId: 'forum-app-g5',
    authDomain: 'forum-app-g5.firebaseapp.com',
    storageBucket: 'forum-app-g5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvp1nbvrVKGD1OgyQmGortKdgy_kolENM',
    appId: '1:823475181285:android:1a85bc87893934d4e7260c',
    messagingSenderId: '823475181285',
    projectId: 'forum-app-g5',
    storageBucket: 'forum-app-g5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCST9avQ11jhN7K2b1ORhYeh7Ep3WPnStE',
    appId: '1:823475181285:ios:d36c06969488eb42e7260c',
    messagingSenderId: '823475181285',
    projectId: 'forum-app-g5',
    storageBucket: 'forum-app-g5.appspot.com',
    iosClientId: '823475181285-r91epiv349688bq40cnb5ldhe6lhd97v.apps.googleusercontent.com',
    iosBundleId: 'com.example.forumApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCST9avQ11jhN7K2b1ORhYeh7Ep3WPnStE',
    appId: '1:823475181285:ios:d36c06969488eb42e7260c',
    messagingSenderId: '823475181285',
    projectId: 'forum-app-g5',
    storageBucket: 'forum-app-g5.appspot.com',
    iosClientId: '823475181285-r91epiv349688bq40cnb5ldhe6lhd97v.apps.googleusercontent.com',
    iosBundleId: 'com.example.forumApp',
  );
}
