// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'firebase_options.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// ...

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJAK5EX0VTmrURtghTcZiMqps_BuH0tak',
    appId: '1:416214302902:web:6e9fd2f3bd81861082e617',
    messagingSenderId: '416214302902',
    projectId: 'forumg5',
    authDomain: 'forumg5.firebaseapp.com',
    storageBucket: 'forumg5.appspot.com',
    measurementId: 'G-9MHHTXXDW2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuaSg2y_PK9yGTlvkh150OqJWiwX8P_l4',
    appId: '1:416214302902:android:abede4f2f879505e82e617',
    messagingSenderId: '416214302902',
    projectId: 'forumg5',
    storageBucket: 'forumg5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXW43HU-u_7EgrkkCOW6w31xjTdLQ_LMs',
    appId: '1:416214302902:ios:1144628dbcd9be5b82e617',
    messagingSenderId: '416214302902',
    projectId: 'forumg5',
    storageBucket: 'forumg5.appspot.com',
    iosClientId:
        '416214302902-vpokjegekerssbsj2e0s84cp6h71avsi.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterForum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXW43HU-u_7EgrkkCOW6w31xjTdLQ_LMs',
    appId: '1:416214302902:ios:1144628dbcd9be5b82e617',
    messagingSenderId: '416214302902',
    projectId: 'forumg5',
    storageBucket: 'forumg5.appspot.com',
    iosClientId:
        '416214302902-vpokjegekerssbsj2e0s84cp6h71avsi.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterForum',
  );
}
